<?php
/**
 * @var \Magento\Framework\View\Element\AbstractBlock $block
 */

// We should use strlen function because coupon code could be "0", converted to bool will lead to false
$hasCouponCode = $block->getCouponCode() !== null && strlen($block->getCouponCode()) > 0;
?>
<!-- jwc -->
<div
    class="cart-discount"
    id="block-discount"
    data-mage-init='{
        "collapsible":{
            "active": true,
            "openedState": "active",
            "saveState": false
        }
    }'
>
    <button
        class="cart-discount__button"
        type="button"
        aria-expanded="false"
        data-role="title"
    >
        <span
            class="cart-discount__button-text"
            id="block-discount-heading"
        >
            <?= $block->escapeHtml(__('Apply Discount Code')) ?>
        </span>

        <svg
            class="icon cart-discount__button-icon"
            role="presentation"
            focusable="false"
        >
            <use href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#angle-down')) ?>"></use>
        </svg>
    </button>

    <div
        class="cart-discount__content"
        data-role="content"
        aria-labelledby="block-discount-heading"
        aria-hidden="<?= $hasCouponCode ? 'true' : 'false' ?>"
    >
        <form
            id="discount-coupon-form"
            class="form"
            action="<?= $block->escapeUrl($block->getUrl('checkout/cart/couponPost')) ?>"
            method="post"
            data-mage-init='{
                "discountCode":{
                    "couponCodeSelector": "#coupon_code",
                    "removeCouponSelector": "#remove-coupon",
                    "applyButton": ".cart-discount__content-button--apply",
                    "cancelButton": ".cart-discount__content-button--cancel"
                }
            }'
        >
            <div
                class="
                    cart-discount__controls
                    <?= $hasCouponCode ? ' applied' : '' ?>
                "
            >
                <input
                    type="hidden"
                    name="remove"
                    id="remove-coupon"
                    value="0"
                >

                <!-- - jwc -->
                <div class="control input cart-discount__content-input">
                    <input
                        type="text"
                        class="input__field cart-discount__content-field"
                        id="coupon_code"
                        name="coupon_code"
                        value="<?= $block->escapeHtmlAttr($block->getCouponCode()) ?>"
                        placeholder="<?= $block->escapeHtmlAttr(__('Enter discount code')) ?>"
                        <?php if ($hasCouponCode): ?>
                           disabled="disabled"
                        <?php endif; ?>
                    >
                    <label
                        for="coupon_code"
                        class="label input__label"
                    >
                        <?= $block->escapeHtml(__('Enter discount code')) ?>
                    </label>
                </div>
                <!-- + jwc -->

                <?php if (!$hasCouponCode): ?>
                    <button
                        class="
                            button
                            cart-discount__content-button
                            cart-discount__content-button--apply
                        "
                        type="button"
                        value="<?= $block->escapeHtmlAttr(__('Apply')) ?>"
                    >
                        <?= $block->escapeHtml(__('Apply')) ?>
                    </button>
                <?php else: ?>
                    <button
                        type="button"
                        class="
                            button
                            cart-discount__content-button
                            cart-discount__content-button--cancel
                        "
                        value="<?= $block->escapeHtmlAttr(__('Cancel')) ?>"
                    >
                        <?= $block->escapeHtml(__('Cancel')) ?>
                    </button>
                <?php endif; ?>
            </div>
            <?php if (!$hasCouponCode): ?>
                <?= /* @noEscape */ $block->getChildHtml('captcha') ?>
            <?php endif; ?>
        </form>
    </div>
</div>
