<div
    data-bind="scope: 'messages'"
    class="messages__wrap"
    aria-live="assertive"
    data-aos="fade-down"
    data-aos-anchor=".header"
    data-aos-anchor-placement="bottom-top"
>
    <div>
        <div
            data-bind="foreach: { data: cookieMessages, as: 'message' }, visible: isVisible()"
            class="messages"
        >
            <div data-bind="
                    visible: $parent.isMessageVisible(message.text), // jwc
                    attr: {
                        class:
                            'message '
                            + 'message--' + message.type
                            + ' ' + message.type,
                        'data-ui-id': 'message-' + message.type,
                    }
                "
            >
                <div data-bind="html: $parent.prepareMessageForHtml(message.text)"></div>
            </div>
        </div>
    </div>
    <div>
        <div
            data-bind="foreach: { data: messages().messages, as: 'message' }, visible: isVisible()"
            class="messages"
        >
            <div data-bind="
                    visible: $parent.isMessageVisible(message.text), // jwc
                    attr: {
                        class:
                            'message '
                            + 'message--' + message.type
                            + ' ' + message.type,
                        'data-ui-id': 'message-' + message.type,
                    }
                "
            >
                <div data-bind="html: $parent.prepareMessageForHtml(message.text)"></div>
            </div>
        </div>
    </div>
    <!-- - jwc -->
    <div class="messages-fbt-wrapper">
        <div id="messagesFBT" class="product-recs-wrapper message"></div>
        <div hidden class="algoliaRecommendCartSvg"><?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#shopping-cart')) ?></div>
        <button class=" button button--icon button--rotate-icon modal__close-button" type="button" aria-label="<?= $block->escapeHtmlAttr(__('Click to close the modal')) ?>" onclick="jQuery('#modal-minicart .modal__close-button').trigger('click')">
            <svg class="icon button__icon modal__close-button-icon" role="presentation" focusable="false"><use href="<?= $block->escapeUrl($block->getViewFileUrl('images/icons-sprite.svg#close')); ?>"></use></svg>
        </button>
    </div>
    <!-- + jwc -->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "messages": {
                        "component": "Magento_Theme/js/view/messages"
                    }
                }
            }
        }
    }
</script>
