<?php
/** @var $block \Magento\Catalog\Block\Product\View */
?>

<?php $_product = $block->getProduct(); ?>
<!-- - jwc -->
<?php $stockStatusText = $_product->getResource()->getAttribute('stock_status_label')->setStoreId($_product->getStoreId())->getFrontend()->getValue($_product); ?>
<?php $stockStatusCode = $_product->getResource()->getAttribute('stock_status_label')->setStoreId(0)->getFrontend()->getValue($_product); ?>
<?php $buttonTitle = __($stockStatusCode === 'pre-order' ? $stockStatusText : 'Add to Cart'); ?>
<!-- + jwc -->

<?php if ($_product->isSaleable()): ?>
        <button
            type="submit"
            title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
            class="
                button
                product-view__add-to-cart
                button--add-to
                action
                tocart
                stock_status_<?=$stockStatusCode?>
            "
            id="product-addtocart-button"
            aria-label="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
        >
            <svg class="icon" role="presentation" focusable="false"><use data-bind="attr: {'href': require.toUrl('images/icons-sprite.svg#shopping-cart')}" href=""></use></svg> <!-- jwc -->
            <span class="button__text">
                <?= $block->escapeHtml($buttonTitle) ?>
            </span>
        </button>

        <?= $block->getChildHtml('', true) ?>
<?php endif; ?>

<?php if ($block->isRedirectToCartEnabled()): ?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "Magento_Catalog/product/view/validation": {
                    "radioCheckboxClosest": ".nested"
                }
            }
        }
    </script>
<?php else: ?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "Magento_Catalog/js/validate-product": {}
            }
        }
    </script>
<?php endif; ?>
