<?php
$product = $block->getProduct();
?>
<?php if (!empty($product['auto_generated_badge'])): ?> <!-- jwc -->
    <?php $productBadges = explode('|', $product['auto_generated_badge']); ?> <!-- jwc -->
    <div
        class="
            badges
            product-view__badges
        "
    >
        <?php if (is_array($productBadges)): ?>
            <?php foreach ($productBadges as $productBadge): ?>
                <div
                    class="
                        badge
                        badge--<?= $block->escapeHtmlAttr(preg_replace('/[[:space:]]+/', '-', mb_strtolower($productBadge, 'UTF-8'))) ?>
                    "
                >
                    <?= $block->escapeHtml($productBadge) ?>
                </div>
            <?php endforeach ?>
        <?php else: ?>
            <div
                class="
                    badge
                    badge--<?= $block->escapeHtmlAttr(preg_replace('/[[:space:]]+/', '-', mb_strtolower($productBadges, 'UTF-8'))) ?>
                "
            >
                <?= $block->escapeHtml($productBadges) ?>
            </div>
        <?php endif ?>
    </div>
<?php endif ?>
